(function(){
  "use strict";
  const PAGE=document.body.dataset.page||"";
  let queued=false;
  function important(element,property,value){if(!element)return;if(element.style.getPropertyValue(property)===value&&element.style.getPropertyPriority(property)==="important")return;element.style.setProperty(property,value,"important")}
  function markInlineField(field,className="db63InlineField"){if(!field)return;field.classList.add(className);important(field,"display","flex");important(field,"grid-template-columns","none");important(field,"flex-direction","row");important(field,"align-items","center");important(field,"gap","8px");important(field,"width","auto");important(field,"min-width","max-content");important(field,"min-height","36px");important(field,"margin","0");important(field,"padding","0");const label=field.querySelector(":scope > label,:scope > small");important(label,"display","block");important(label,"position","static");important(label,"width","auto");important(label,"min-width","auto");important(label,"margin","0");important(label,"padding","0");important(label,"white-space","nowrap")}
  function fixQueue(){if(PAGE!=="queue")return;const toolbar=document.querySelector(".queueWorkspaceToolbar,.queueOpsToolbar");const filters=toolbar?.querySelector(".queueToolbarFilters")||document.querySelector(".queueToolbarFilters");const dateField=document.getElementById("queueDate")?.closest(".filterField");const viewField=document.getElementById("queueStatus")?.closest(".filterField");const quick=toolbar?.querySelector(".queueToolbarQuickActions")||document.querySelector(".queueToolbarQuickActions");if(!toolbar||!filters)return;toolbar.classList.add("db63QueueToolbar");filters.classList.add("db63QueueFilters");quick?.classList.add("db63QueueQuickActions");markInlineField(dateField);markInlineField(viewField);important(toolbar,"display","flex");important(toolbar,"grid-template-columns","none");important(toolbar,"flex-flow","row nowrap");important(toolbar,"align-items","center");important(toolbar,"gap","10px");important(toolbar,"padding","8px 10px");important(filters,"display","flex");important(filters,"grid-template-columns","none");important(filters,"flex-flow","row nowrap");important(filters,"align-items","center");important(filters,"flex","1 1 auto");important(filters,"min-width","0");important(filters,"gap","12px");important(filters,"padding","0");important(document.getElementById("queueDate"),"width","142px");important(document.getElementById("queueStatus"),"width","122px");if(quick){important(quick,"display","flex");important(quick,"flex","0 0 auto");important(quick,"align-items","center");important(quick,"gap","8px");important(quick,"margin","0");important(quick,"padding","0")}}
  function fixDashboardControls(){if(PAGE!=="dashboard")return;const toolbar=document.querySelector(".dashboardWorkspaceToolbar,.dashboardFilters");const operational=toolbar?.querySelector(".dashboardOperationalControls")||toolbar;const dateField=document.getElementById("adminDate")?.closest(".filterField");const statusField=document.getElementById("adminStatus")?.closest(".filterField");const rangeField=document.querySelector(".dashboardRangeHost > .rangeMetric,.dashboardRangeHost .rangeMetric");if(!toolbar||!operational)return;toolbar.classList.add("db63DashboardToolbar");operational.classList.add("db63DashboardOperational");markInlineField(dateField);markInlineField(statusField);markInlineField(rangeField,"db63RangeField");important(toolbar,"display","flex");important(toolbar,"align-items","center");important(toolbar,"gap","12px");important(toolbar,"padding","8px 10px");important(operational,"display","flex");important(operational,"grid-template-columns","none");important(operational,"flex-flow","row nowrap");important(operational,"align-items","center");important(operational,"flex","1 1 auto");important(operational,"min-width","0");important(operational,"gap","14px");important(document.getElementById("adminDate"),"width","148px");important(document.getElementById("adminStatus"),"width","150px");important(document.getElementById("dashboardRange"),"width","142px")}
  function fixReports(){if(PAGE!=="reports")return;const filters=document.querySelector(".reportFilters");if(!filters)return;filters.classList.add("db63ReportFilters");filters.querySelectorAll(":scope > .filterField").forEach(field=>markInlineField(field));filters.querySelectorAll(".reportCustomDates > .filterField").forEach(field=>markInlineField(field));important(filters,"display","flex");important(filters,"grid-template-columns","none");important(filters,"flex-flow","row wrap");important(filters,"align-items","center");important(filters,"gap","10px 16px");important(filters,"padding","8px 10px");important(document.getElementById("reportView"),"width","220px");important(document.getElementById("reportPreset"),"width","154px")}
  function fixAppointmentGap(){if(PAGE!=="myappointments")return;const metrics=document.getElementById("myAppointmentMetrics");if(!metrics||metrics.hidden)return;const compact=window.matchMedia("(max-width:760px)").matches;important(metrics,"height",compact?"auto":"92px");important(metrics,"min-height",compact?"0":"92px");important(metrics,"max-height",compact?"none":"92px");important(metrics,"grid-auto-rows",compact?"86px":"92px");important(metrics,"align-content","start");important(metrics,"margin","0");important(metrics,"padding","0");const spotlight=metrics.nextElementSibling;if(spotlight?.matches(".nextAppointmentSpotlight")&&spotlight.hidden){important(spotlight,"display","none");important(spotlight,"height","0");important(spotlight,"min-height","0");important(spotlight,"margin","0");important(spotlight,"padding","0")}let sibling=metrics.nextElementSibling;while(sibling){if(sibling.matches(".panel"))important(sibling,"margin-top","10px");sibling=sibling.nextElementSibling}}
  function dashboardMetricKey(card){return String(card.dataset.metricKey||card.querySelector(":scope > small")?.textContent||"").trim().toLowerCase().replace(/\s+/g,"-")}
  function fixDashboardMetrics(){if(PAGE!=="dashboard")return;const metrics=document.getElementById("metrics");const showToggle=document.getElementById("dashboardShowMetrics");const inputs=[...document.querySelectorAll('.dashboardCustomizeOptions input[type="checkbox"]')];if(!metrics||!inputs.length)return;inputs.forEach(input=>{input.disabled=false;input.removeAttribute("disabled")});const selected=new Set(inputs.filter(input=>input.checked).map(input=>input.value));const showMetrics=showToggle?showToggle.checked:!metrics.hidden;metrics.hidden=!showMetrics;important(metrics,"display",showMetrics?"grid":"none");if(!showMetrics)return;let visible=0;metrics.querySelectorAll(":scope > .metric:not(.rangeMetric)").forEach(card=>{const key=dashboardMetricKey(card);const show=selected.has(key);card.hidden=!show;important(card,"display",show?"grid":"none");if(show)visible++});const count=Math.max(1,visible);metrics.style.setProperty("--db63-dashboard-columns",String(count));if(window.matchMedia("(min-width:1181px)").matches)important(metrics,"grid-template-columns",`repeat(${count},minmax(0,1fr))`)}
  function apply(){document.body.classList.add("db63ScreenshotFix");fixQueue();fixDashboardControls();fixReports();fixAppointmentGap();fixDashboardMetrics()}
  function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply()})}
  function initialize(){apply();document.addEventListener("change",event=>{if(event.target.matches('.dashboardCustomizeOptions input[type="checkbox"],#dashboardShowMetrics,#reportView,#reportPreset,#myAppointmentFilter')){window.setTimeout(schedule,0);window.setTimeout(schedule,80)}},true);window.addEventListener("resize",schedule,{passive:true});new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});[50,150,350,700,1200,2200,4000].forEach(delay=>window.setTimeout(apply,delay))}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialize,{once:true});else initialize();
})();
