-- MaxDock DB21 / database v14
-- Five-second live views, optional skid-capacity planning, and a secure MIS import foundation.

begin;

alter table public.location_settings
  add column if not exists capacity_enabled boolean not null default false,
  add column if not exists skid_capacity integer,
  add column if not exists capacity_reserve_skids integer not null default 0,
  add column if not exists capacity_enforcement_mode text not null default 'warn',
  add column if not exists current_occupied_skids integer not null default 0,
  add column if not exists inventory_as_of timestamptz,
  add column if not exists capacity_last_source text not null default 'manual';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'location_settings_skid_capacity_check') then
    alter table public.location_settings
      add constraint location_settings_skid_capacity_check
      check (skid_capacity is null or skid_capacity > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'location_settings_capacity_reserve_check') then
    alter table public.location_settings
      add constraint location_settings_capacity_reserve_check
      check (capacity_reserve_skids >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'location_settings_capacity_mode_check') then
    alter table public.location_settings
      add constraint location_settings_capacity_mode_check
      check (capacity_enforcement_mode in ('warn', 'enforce'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'location_settings_current_occupied_check') then
    alter table public.location_settings
      add constraint location_settings_current_occupied_check
      check (current_occupied_skids >= 0);
  end if;
end
$$;

create table if not exists public.location_inventory_snapshots (
  id bigint generated by default as identity primary key,
  location_id uuid not null references public.locations(id) on delete cascade,
  snapshot_at timestamptz not null,
  occupied_skids integer not null check (occupied_skids >= 0),
  total_skid_capacity integer check (total_skid_capacity is null or total_skid_capacity > 0),
  reserve_skids integer check (reserve_skids is null or reserve_skids >= 0),
  source text not null default 'manual_csv',
  source_file_name text,
  notes text,
  imported_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (location_id, snapshot_at, source)
);

comment on table public.location_inventory_snapshots is
  'Warehouse skid-occupancy snapshots used as the baseline for capacity projections.';

create index if not exists location_inventory_snapshots_lookup_idx
  on public.location_inventory_snapshots(location_id, snapshot_at desc);

alter table public.location_inventory_snapshots enable row level security;
revoke all on public.location_inventory_snapshots from public, anon, authenticated;

create table if not exists public.mis_integration_settings (
  id smallint primary key default 1 check (id = 1),
  database_type text not null default 'sql_server'
    check (database_type in ('sql_server', 'postgresql', 'mysql', 'oracle', 'other')),
  server_name text,
  server_port integer check (server_port is null or server_port between 1 and 65535),
  database_name text,
  source_name text,
  sync_mode text not null default 'manual_csv'
    check (sync_mode in ('manual_csv', 'secure_bridge')),
  daily_sync_time time not null default '05:00',
  is_enabled boolean not null default false,
  credential_secret_name text,
  last_success_at timestamptz,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.mis_integration_settings is
  'Non-secret MIS connection metadata. Credentials must be stored as server-side secrets, never in the browser.';

alter table public.mis_integration_settings enable row level security;
revoke all on public.mis_integration_settings from public, anon, authenticated;

insert into public.mis_integration_settings(id)
values (1)
on conflict (id) do nothing;

create table if not exists public.mis_import_runs (
  id bigint generated by default as identity primary key,
  import_type text not null default 'inventory_snapshot',
  file_name text,
  row_count integer not null default 0 check (row_count >= 0),
  status text not null check (status in ('completed', 'failed')),
  summary text,
  imported_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.mis_import_runs enable row level security;
revoke all on public.mis_import_runs from public, anon, authenticated;

create index if not exists mis_import_runs_created_idx
  on public.mis_import_runs(created_at desc);

create or replace function public.get_location_capacity_projection(
  p_location_id uuid,
  p_at timestamptz,
  p_direction text default 'inbound',
  p_skid_count integer default 0,
  p_exclude_appointment_id uuid default null
)
returns table (
  capacity_enabled boolean,
  enforcement_mode text,
  total_capacity integer,
  reserve_skids integer,
  baseline_occupied integer,
  projected_before integer,
  projected_after integer,
  available_after integer,
  can_accept boolean,
  capacity_message text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_enabled boolean;
  v_mode text;
  v_total integer;
  v_reserve integer;
  v_baseline integer;
  v_as_of timestamptz;
  v_delta integer;
  v_before integer;
  v_after integer;
  v_limit integer;
  v_can_accept boolean;
  v_direction text := lower(trim(coalesce(p_direction, '')));
  v_message text;
begin
  if auth.uid() is null then raise exception 'You must be signed in to view warehouse capacity.'; end if;
  if not public.has_location_access(p_location_id) then
    raise exception 'You do not have access to this MaxDock location.';
  end if;
  if p_at is null then raise exception 'A capacity projection time is required.'; end if;
  if v_direction not in ('inbound', 'outbound') then raise exception 'Direction must be inbound or outbound.'; end if;
  if coalesce(p_skid_count, 0) < 0 then raise exception 'Skid count cannot be negative.'; end if;

  select
    ls.capacity_enabled,
    ls.capacity_enforcement_mode,
    ls.skid_capacity,
    ls.capacity_reserve_skids,
    ls.current_occupied_skids,
    ls.inventory_as_of
  into v_enabled, v_mode, v_total, v_reserve, v_baseline, v_as_of
  from public.location_settings ls
  where ls.location_id = p_location_id and ls.is_active = true;

  if not found then raise exception 'The selected location is not configured.'; end if;

  v_enabled := coalesce(v_enabled, false) and v_total is not null;
  v_mode := coalesce(v_mode, 'warn');
  v_reserve := greatest(coalesce(v_reserve, 0), 0);
  v_baseline := greatest(coalesce(v_baseline, 0), 0);
  v_as_of := coalesce(v_as_of, now());

  select coalesce(sum(
    case lower(coalesce(a.direction, ''))
      when 'inbound' then greatest(coalesce(a.skid_count, 0), 0)
      when 'outbound' then -greatest(coalesce(a.skid_count, 0), 0)
      else 0
    end
  ), 0)::integer
  into v_delta
  from public.appointments a
  where a.location_id = p_location_id
    and a.entry_kind = 'appointment'
    and a.status not in ('cancelled', 'no_show')
    and a.start_at >= v_as_of
    and a.start_at <= p_at
    and (p_exclude_appointment_id is null or a.id <> p_exclude_appointment_id);

  v_before := greatest(v_baseline + coalesce(v_delta, 0), 0);
  v_after := greatest(v_before + case when v_direction = 'inbound' then coalesce(p_skid_count, 0) else -coalesce(p_skid_count, 0) end, 0);
  v_limit := greatest(coalesce(v_total, 0) - v_reserve, 0);
  v_can_accept := not v_enabled or v_direction = 'outbound' or v_after <= v_limit;

  if not v_enabled then
    v_message := 'Warehouse skid-capacity control is not enabled.';
  elsif v_can_accept then
    v_message := format('%s skid spaces remain after this appointment.', greatest(v_limit - v_after, 0));
  else
    v_message := format('Projected occupancy is %s skids; the working limit is %s.', v_after, v_limit);
  end if;

  return query select
    v_enabled, v_mode, v_total, v_reserve, v_baseline,
    v_before, v_after, greatest(v_limit - v_after, 0), v_can_accept, v_message;
end;
$$;

revoke all on function public.get_location_capacity_projection(uuid, timestamptz, text, integer, uuid) from public, anon;
grant execute on function public.get_location_capacity_projection(uuid, timestamptz, text, integer, uuid) to authenticated;

create or replace function public.list_capacity_aware_appointment_slots(
  p_location_id uuid,
  p_date date,
  p_direction text,
  p_appointment_type_code text,
  p_truck_type_code text,
  p_skid_count integer,
  p_handling_type_code text,
  p_is_priority boolean default false,
  p_preferred_start_time time default null,
  p_preferred_end_time time default null,
  p_search_days integer default 7
)
returns table (
  slot_start timestamptz,
  slot_end timestamptz,
  available_docks integer,
  recommendation_rank integer,
  recommendation_score integer,
  recommended_dock_id uuid,
  recommended_dock_name text,
  recommendation_reason text,
  capacity_enabled boolean,
  capacity_warning boolean,
  projected_occupied_skids integer,
  available_skid_capacity integer,
  capacity_message text,
  alternative_date boolean
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_timezone text;
  v_direction text := lower(trim(coalesce(p_direction, '')));
begin
  if auth.uid() is null then raise exception 'You must be signed in to view available appointment times.'; end if;
  if v_direction not in ('inbound', 'outbound') then raise exception 'Direction must be inbound or outbound.'; end if;
  if p_date is null then raise exception 'An appointment date is required.'; end if;
  if coalesce(p_search_days, 0) not between 0 and 30 then raise exception 'Capacity search days must be between 0 and 30.'; end if;

  select l.timezone into v_timezone
  from public.locations l
  where l.id = p_location_id and l.is_active = true;
  if not found then raise exception 'The selected location is inactive.'; end if;

  return query
  with candidate_dates as (
    select (p_date + offset_value)::date as candidate_date
    from generate_series(0, least(greatest(coalesce(p_search_days, 0), 0), 30)) offset_value
  ), slots as (
    select dates.candidate_date, slot.*
    from candidate_dates dates
    cross join lateral public.list_smart_appointment_slots(
      p_location_id,
      dates.candidate_date,
      p_appointment_type_code,
      p_truck_type_code,
      p_skid_count,
      p_handling_type_code,
      p_is_priority,
      p_preferred_start_time,
      p_preferred_end_time
    ) slot
  ), assessed as (
    select
      slots.*,
      capacity.capacity_enabled,
      capacity.enforcement_mode,
      capacity.projected_after,
      capacity.available_after,
      capacity.can_accept,
      capacity.capacity_message,
      (slots.slot_start at time zone v_timezone)::date as local_slot_date
    from slots
    cross join lateral public.get_location_capacity_projection(
      p_location_id,
      slots.slot_start,
      v_direction,
      p_skid_count,
      null
    ) capacity
  ), eligible as (
    select assessed.*
    from assessed
    where not assessed.capacity_enabled
       or assessed.enforcement_mode = 'warn'
       or assessed.can_accept
  ), first_available as (
    select min(eligible.local_slot_date) as available_date from eligible
  ), ranked as (
    select
      eligible.*,
      row_number() over (
        order by
          (eligible.recommendation_score - case when eligible.capacity_enabled and not eligible.can_accept then 500 else 0 end) desc,
          eligible.slot_start
      )::integer as final_rank
    from eligible
    cross join first_available
    where eligible.local_slot_date = first_available.available_date
  )
  select
    ranked.slot_start,
    ranked.slot_end,
    ranked.available_docks,
    ranked.final_rank,
    (ranked.recommendation_score - case when ranked.capacity_enabled and not ranked.can_accept then 500 else 0 end)::integer,
    ranked.recommended_dock_id,
    ranked.recommended_dock_name,
    concat_ws(
      ' · ',
      case when ranked.local_slot_date > p_date then format('Next capacity-ready date: %s', to_char(ranked.local_slot_date, 'Mon DD')) end,
      ranked.recommendation_reason,
      case when ranked.capacity_enabled then ranked.capacity_message end
    ),
    ranked.capacity_enabled,
    (ranked.capacity_enabled and not ranked.can_accept),
    ranked.projected_after,
    ranked.available_after,
    ranked.capacity_message,
    (ranked.local_slot_date > p_date)
  from ranked
  order by ranked.slot_start;
end;
$$;

revoke all on function public.list_capacity_aware_appointment_slots(uuid, date, text, text, text, integer, text, boolean, time, time, integer) from public, anon;
grant execute on function public.list_capacity_aware_appointment_slots(uuid, date, text, text, text, integer, text, boolean, time, time, integer) to authenticated;

create or replace function public.book_appointment(
  p_location_id uuid,
  p_date date,
  p_start_time time,
  p_direction text,
  p_requester_type text,
  p_appointment_type_code text,
  p_truck_type_code text,
  p_skid_count integer,
  p_handling_type_code text,
  p_is_priority boolean,
  p_requester_name text,
  p_requester_email text,
  p_external_reference text,
  p_company_name text default null,
  p_requester_location_id uuid default null,
  p_carrier_name text default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_timezone text;
  v_slot_interval integer;
  v_minimum_notice integer;
  v_maximum_advance integer;
  v_is_open boolean;
  v_open_time time;
  v_close_time time;
  v_open_at timestamptz;
  v_close_at timestamptz;
  v_start_at timestamptz;
  v_end_at timestamptz;
  v_duration integer;
  v_local_today date;
  v_dock_id uuid;
  v_dock_name text;
  v_appointment public.appointments%rowtype;
  v_capacity_enabled boolean;
  v_capacity_mode text;
  v_projected_after integer;
  v_available_after integer;
  v_capacity_allowed boolean;
  v_capacity_message text;
begin
  if auth.uid() is null then raise exception 'You must be signed in to book an appointment.'; end if;
  if not public.has_location_access(p_location_id)
     or not public.has_permission('appointment.create') then
    raise exception 'You do not have permission to create appointments for this location.';
  end if;
  if p_date is null or p_start_time is null then raise exception 'Appointment date and start time are required.'; end if;
  if lower(coalesce(p_direction, '')) not in ('inbound', 'outbound') then raise exception 'Direction must be inbound or outbound.'; end if;
  if p_skid_count is null or p_skid_count < 0 then raise exception 'Skid count cannot be negative.'; end if;
  if nullif(trim(coalesce(p_requester_type, '')), '') is null then raise exception 'Requester type is required.'; end if;
  if nullif(trim(coalesce(p_requester_name, '')), '') is null then raise exception 'Requester name is required.'; end if;
  if nullif(trim(coalesce(p_requester_email, '')), '') is null
     or position('@' in p_requester_email) <= 1 then raise exception 'A valid requester email is required.'; end if;
  if nullif(trim(coalesce(p_external_reference, '')), '') is null then raise exception 'PO / BOL / Job number is required.'; end if;

  select l.timezone, ls.slot_interval_minutes, ls.minimum_notice_minutes, ls.maximum_advance_days
  into v_timezone, v_slot_interval, v_minimum_notice, v_maximum_advance
  from public.locations l
  join public.location_settings ls on ls.location_id = l.id
  where l.id = p_location_id and l.is_active and ls.is_active;
  if not found then raise exception 'The selected location is inactive or not configured.'; end if;

  v_local_today := (now() at time zone v_timezone)::date;
  if p_date < v_local_today then raise exception 'Appointments cannot be created in the past.'; end if;
  if p_date > v_local_today + v_maximum_advance then raise exception 'The selected date is beyond this location''s booking window.'; end if;

  select oh.is_open, oh.open_time, oh.close_time
  into v_is_open, v_open_time, v_close_time
  from public.location_operating_hours oh
  where oh.location_id = p_location_id
    and oh.day_of_week = extract(dow from p_date)::smallint;
  if not found or not v_is_open then raise exception 'The selected location is closed on this date.'; end if;

  v_duration := public.calculate_appointment_duration(
    p_location_id, p_appointment_type_code, p_truck_type_code,
    p_skid_count, p_handling_type_code, p_is_priority
  );
  v_open_at := (p_date + v_open_time) at time zone v_timezone;
  v_close_at := (p_date + v_close_time) at time zone v_timezone;
  v_start_at := (p_date + p_start_time) at time zone v_timezone;
  v_end_at := v_start_at + make_interval(mins => v_duration);

  if v_start_at < now() + make_interval(mins => v_minimum_notice) then raise exception 'The selected time does not meet this location''s minimum notice.'; end if;
  if v_start_at < v_open_at or v_end_at > v_close_at then raise exception 'The appointment must fit within the location''s operating hours.'; end if;
  if mod((extract(epoch from (v_start_at - v_open_at)) / 60)::integer, v_slot_interval) <> 0 then
    raise exception 'The selected time is not aligned with the location''s slot interval.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_location_id::text || ':' || p_date::text, 0));

  select
    capacity.capacity_enabled,
    capacity.enforcement_mode,
    capacity.projected_after,
    capacity.available_after,
    capacity.can_accept,
    capacity.capacity_message
  into
    v_capacity_enabled,
    v_capacity_mode,
    v_projected_after,
    v_available_after,
    v_capacity_allowed,
    v_capacity_message
  from public.get_location_capacity_projection(
    p_location_id, v_start_at, lower(p_direction), p_skid_count, null
  ) capacity;

  if v_capacity_enabled and v_capacity_mode = 'enforce' and not v_capacity_allowed then
    raise exception 'This inbound load exceeds the location''s working skid capacity. Choose one of the later suggested times.';
  end if;

  select d.id, d.name
  into v_dock_id, v_dock_name
  from public.docks d
  join public.dock_truck_types dtt
    on dtt.dock_id = d.id
   and dtt.location_id = p_location_id
   and dtt.truck_type_code = p_truck_type_code
  where d.location_id = p_location_id
    and d.is_active
    and not exists (
      select 1 from public.appointments conflict
      where conflict.dock_id = d.id
        and conflict.status <> 'cancelled'
        and conflict.schedule_range && tstzrange(v_start_at, v_end_at, '[)')
    )
  order by
    coalesce((
      select sum(extract(epoch from (day_load.end_at - day_load.start_at)) / 60)
      from public.appointments day_load
      where day_load.dock_id = d.id
        and day_load.status <> 'cancelled'
        and (day_load.start_at at time zone v_timezone)::date = p_date
    ), 0),
    d.sort_order,
    d.name
  limit 1;

  if v_dock_id is null then raise exception 'No compatible dock is available at the selected time.'; end if;

  insert into public.appointments (
    booking_reference, entry_kind, source, location_id, dock_id, start_at, end_at,
    direction, requester_type, requester_location_id, company_name,
    appointment_type_code, truck_type_code, skid_count, handling_type_code,
    is_priority, requester_name, requester_email, carrier_name,
    external_reference, notes, status, created_by, updated_by
  ) values (
    null, 'appointment', 'internal', p_location_id, v_dock_id, v_start_at, v_end_at,
    lower(p_direction), trim(p_requester_type), p_requester_location_id,
    nullif(trim(coalesce(p_company_name, '')), ''), p_appointment_type_code,
    p_truck_type_code, p_skid_count, p_handling_type_code,
    coalesce(p_is_priority, false), trim(p_requester_name),
    lower(trim(p_requester_email)), nullif(trim(coalesce(p_carrier_name, '')), ''),
    trim(p_external_reference), nullif(trim(coalesce(p_notes, '')), ''),
    'scheduled', auth.uid(), auth.uid()
  ) returning * into v_appointment;

  return jsonb_build_object(
    'appointment_id', v_appointment.id,
    'booking_reference', v_appointment.booking_reference,
    'dock_id', v_dock_id,
    'dock_name', v_dock_name,
    'start_at', v_appointment.start_at,
    'end_at', v_appointment.end_at,
    'status', v_appointment.status,
    'capacity_enabled', v_capacity_enabled,
    'projected_occupied_skids', v_projected_after,
    'available_skid_capacity', v_available_after,
    'capacity_message', v_capacity_message
  );
end;
$$;

create or replace function public.update_appointment_details(
  p_appointment_id uuid,
  p_date date,
  p_start_time time,
  p_dock_id uuid,
  p_direction text,
  p_company_name text,
  p_appointment_type_code text,
  p_truck_type_code text,
  p_skid_count integer,
  p_handling_type_code text,
  p_is_priority boolean,
  p_requester_name text,
  p_requester_email text,
  p_carrier_name text,
  p_external_reference text,
  p_notes text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_appointment public.appointments%rowtype;
  v_timezone text;
  v_slot_interval integer;
  v_open_time time;
  v_close_time time;
  v_is_open boolean;
  v_local_today date;
  v_start_at timestamptz;
  v_end_at timestamptz;
  v_open_at timestamptz;
  v_close_at timestamptz;
  v_duration integer;
  v_capacity_enabled boolean;
  v_capacity_mode text;
  v_capacity_allowed boolean;
begin
  if auth.uid() is null then raise exception 'You must be signed in to edit an appointment.'; end if;
  if public.current_maxdock_role() not in ('system_admin', 'site_admin')
     or not public.has_permission('appointment.update') then
    raise exception 'Only a MaxDock System Admin or Site Admin can edit appointments.';
  end if;

  select * into v_appointment
  from public.appointments a
  where a.id = p_appointment_id
  for update;
  if not found then raise exception 'Appointment not found.'; end if;
  if v_appointment.entry_kind <> 'appointment' then raise exception 'Dock blocks must be managed with the Block Dock Time controls.'; end if;
  if v_appointment.status in ('completed', 'cancelled', 'no_show') then raise exception 'Completed, cancelled, and no-show appointments cannot be edited.'; end if;
  if not public.has_location_access(v_appointment.location_id) then raise exception 'You do not have access to this appointment''s location.'; end if;
  if p_date is null or p_start_time is null or p_dock_id is null then raise exception 'Date, start time, and dock are required.'; end if;
  if lower(trim(coalesce(p_direction, ''))) not in ('inbound', 'outbound') then raise exception 'Direction must be inbound or outbound.'; end if;
  if p_skid_count is null or p_skid_count < 0 then raise exception 'Skid count cannot be negative.'; end if;
  if nullif(trim(coalesce(p_requester_name, '')), '') is null then raise exception 'Requester name is required.'; end if;
  if nullif(trim(coalesce(p_requester_email, '')), '') is null or position('@' in p_requester_email) <= 1 then raise exception 'A valid requester email is required.'; end if;
  if nullif(trim(coalesce(p_external_reference, '')), '') is null then raise exception 'PO / BOL / Job number is required.'; end if;

  select l.timezone, ls.slot_interval_minutes
  into v_timezone, v_slot_interval
  from public.locations l
  join public.location_settings ls on ls.location_id = l.id
  where l.id = v_appointment.location_id and l.is_active = true and ls.is_active = true;
  if not found then raise exception 'The appointment location is inactive or not configured.'; end if;

  v_local_today := (now() at time zone v_timezone)::date;
  if p_date < v_local_today then raise exception 'An active appointment cannot be moved to a past date.'; end if;

  select oh.is_open, oh.open_time, oh.close_time
  into v_is_open, v_open_time, v_close_time
  from public.location_operating_hours oh
  where oh.location_id = v_appointment.location_id
    and oh.day_of_week = extract(dow from p_date)::smallint;
  if not found or not v_is_open then raise exception 'The selected location is closed on this date.'; end if;

  if not exists (
    select 1 from public.docks d
    where d.id = p_dock_id and d.location_id = v_appointment.location_id and d.is_active = true
  ) then raise exception 'The selected dock is invalid or inactive.'; end if;

  v_duration := public.calculate_appointment_duration(
    v_appointment.location_id, p_appointment_type_code, p_truck_type_code,
    p_skid_count, p_handling_type_code, coalesce(p_is_priority, false)
  );
  v_open_at := (p_date + v_open_time) at time zone v_timezone;
  v_close_at := (p_date + v_close_time) at time zone v_timezone;
  v_start_at := (p_date + p_start_time) at time zone v_timezone;
  v_end_at := v_start_at + make_interval(mins => v_duration);

  if v_start_at < v_open_at or v_end_at > v_close_at then raise exception 'The edited appointment must fit within the location''s operating hours.'; end if;
  if mod((extract(epoch from (v_start_at - v_open_at)) / 60)::integer, v_slot_interval) <> 0 then
    raise exception 'The start time is not aligned with the location''s slot interval.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_appointment.location_id::text || ':' || p_date::text, 0));

  select capacity.capacity_enabled, capacity.enforcement_mode, capacity.can_accept
  into v_capacity_enabled, v_capacity_mode, v_capacity_allowed
  from public.get_location_capacity_projection(
    v_appointment.location_id, v_start_at, lower(p_direction), p_skid_count, p_appointment_id
  ) capacity;
  if v_capacity_enabled and v_capacity_mode = 'enforce' and not v_capacity_allowed then
    raise exception 'This edit exceeds the location''s working skid capacity. Choose a later time or reduce the inbound skid count.';
  end if;

  if exists (
    select 1 from public.appointments a
    where a.id <> p_appointment_id
      and a.dock_id = p_dock_id
      and a.status <> 'cancelled'
      and a.schedule_range && tstzrange(v_start_at, v_end_at, '[)')
  ) then raise exception 'The selected dock and time overlap another appointment or dock block.'; end if;

  update public.appointments
  set dock_id = p_dock_id,
      start_at = v_start_at,
      end_at = v_end_at,
      direction = lower(trim(p_direction)),
      company_name = nullif(trim(coalesce(p_company_name, '')), ''),
      appointment_type_code = p_appointment_type_code,
      truck_type_code = p_truck_type_code,
      skid_count = p_skid_count,
      handling_type_code = p_handling_type_code,
      is_priority = coalesce(p_is_priority, false),
      requester_name = trim(p_requester_name),
      requester_email = lower(trim(p_requester_email)),
      carrier_name = nullif(trim(coalesce(p_carrier_name, '')), ''),
      external_reference = trim(p_external_reference),
      notes = nullif(trim(coalesce(p_notes, '')), ''),
      updated_by = auth.uid()
  where id = p_appointment_id
  returning * into v_appointment;

  return jsonb_build_object(
    'appointment_id', v_appointment.id,
    'booking_reference', v_appointment.booking_reference,
    'dock_id', v_appointment.dock_id,
    'start_at', v_appointment.start_at,
    'end_at', v_appointment.end_at,
    'status', v_appointment.status
  );
end;
$$;

revoke all on function public.book_appointment(uuid, date, time, text, text, text, text, integer, text, boolean, text, text, text, text, uuid, text, text) from public, anon;
grant execute on function public.book_appointment(uuid, date, time, text, text, text, text, integer, text, boolean, text, text, text, text, uuid, text, text) to authenticated;
revoke all on function public.update_appointment_details(uuid, date, time, uuid, text, text, text, text, integer, text, boolean, text, text, text, text, text) from public, anon;
grant execute on function public.update_appointment_details(uuid, date, time, uuid, text, text, text, text, integer, text, boolean, text, text, text, text, text) to authenticated;

create or replace function public.admin_get_mis_integration_settings()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_settings public.mis_integration_settings%rowtype;
begin
  if auth.uid() is null then raise exception 'You must be signed in to view MIS settings.'; end if;
  if not public.is_system_admin() then raise exception 'Only a MaxDock System Admin can view MIS settings.'; end if;

  select * into v_settings from public.mis_integration_settings where id = 1;
  return jsonb_build_object(
    'database_type', v_settings.database_type,
    'server_name', coalesce(v_settings.server_name, ''),
    'server_port', v_settings.server_port,
    'database_name', coalesce(v_settings.database_name, ''),
    'source_name', coalesce(v_settings.source_name, ''),
    'sync_mode', v_settings.sync_mode,
    'daily_sync_time', to_char(v_settings.daily_sync_time, 'HH24:MI'),
    'is_enabled', v_settings.is_enabled,
    'credential_secret_name', coalesce(v_settings.credential_secret_name, ''),
    'last_success_at', v_settings.last_success_at
  );
end;
$$;

create or replace function public.admin_save_mis_integration_settings(
  p_database_type text,
  p_server_name text,
  p_server_port integer,
  p_database_name text,
  p_source_name text,
  p_sync_mode text,
  p_daily_sync_time time,
  p_is_enabled boolean,
  p_credential_secret_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'You must be signed in to save MIS settings.'; end if;
  if not public.is_system_admin() then raise exception 'Only a MaxDock System Admin can save MIS settings.'; end if;
  if p_database_type not in ('sql_server', 'postgresql', 'mysql', 'oracle', 'other') then raise exception 'The MIS database type is invalid.'; end if;
  if p_sync_mode not in ('manual_csv', 'secure_bridge') then raise exception 'The MIS synchronization mode is invalid.'; end if;
  if p_server_port is not null and p_server_port not between 1 and 65535 then raise exception 'The MIS server port is invalid.'; end if;
  if p_sync_mode = 'secure_bridge' and (
    nullif(trim(coalesce(p_server_name, '')), '') is null
    or nullif(trim(coalesce(p_database_name, '')), '') is null
  ) then raise exception 'Server and database names are required for the secure bridge.'; end if;

  insert into public.mis_integration_settings(
    id, database_type, server_name, server_port, database_name, source_name,
    sync_mode, daily_sync_time, is_enabled, credential_secret_name, updated_by, updated_at
  ) values (
    1, p_database_type, nullif(trim(coalesce(p_server_name, '')), ''), p_server_port,
    nullif(trim(coalesce(p_database_name, '')), ''), nullif(trim(coalesce(p_source_name, '')), ''),
    p_sync_mode, coalesce(p_daily_sync_time, '05:00'::time), coalesce(p_is_enabled, false),
    nullif(trim(coalesce(p_credential_secret_name, '')), ''), auth.uid(), now()
  )
  on conflict (id) do update
  set database_type = excluded.database_type,
      server_name = excluded.server_name,
      server_port = excluded.server_port,
      database_name = excluded.database_name,
      source_name = excluded.source_name,
      sync_mode = excluded.sync_mode,
      daily_sync_time = excluded.daily_sync_time,
      is_enabled = excluded.is_enabled,
      credential_secret_name = excluded.credential_secret_name,
      updated_by = auth.uid(),
      updated_at = now();

  return public.admin_get_mis_integration_settings();
end;
$$;

create or replace function public.admin_import_inventory_snapshots(
  p_rows jsonb,
  p_file_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row jsonb;
  v_location public.locations%rowtype;
  v_location_code text;
  v_snapshot_text text;
  v_snapshot_at timestamptz;
  v_occupied integer;
  v_total integer;
  v_reserve integer;
  v_notes text;
  v_count integer := 0;
begin
  if auth.uid() is null then raise exception 'You must be signed in to import MIS data.'; end if;
  if not public.is_system_admin() then raise exception 'Only a MaxDock System Admin can import MIS data.'; end if;
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then raise exception 'The MIS import must be a JSON row array.'; end if;
  if jsonb_array_length(p_rows) = 0 then raise exception 'The MIS import file is empty.'; end if;
  if jsonb_array_length(p_rows) > 1000 then raise exception 'A maximum of 1,000 inventory rows can be imported at once.'; end if;

  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    v_location_code := upper(trim(coalesce(v_row->>'location_code', '')));
    v_snapshot_text := trim(coalesce(v_row->>'snapshot_at', ''));
    if v_location_code = '' then raise exception 'Every import row requires location_code.'; end if;
    if v_snapshot_text = '' then raise exception 'Every import row requires snapshot_at.'; end if;
    if coalesce(v_row->>'occupied_skids', '') !~ '^[0-9]+$' then raise exception 'occupied_skids must be a whole number.'; end if;

    select * into v_location
    from public.locations l
    where upper(l.code) = v_location_code and l.is_active = true;
    if not found then raise exception 'Unknown or inactive MaxDock location code: %', v_location_code; end if;

    begin
      if v_snapshot_text ~ '(Z|[+-][0-9]{2}:[0-9]{2})$' then
        v_snapshot_at := v_snapshot_text::timestamptz;
      else
        v_snapshot_at := v_snapshot_text::timestamp at time zone v_location.timezone;
      end if;
    exception when others then
      raise exception 'Invalid snapshot_at for location %: %', v_location_code, v_snapshot_text;
    end;

    v_occupied := (v_row->>'occupied_skids')::integer;
    v_total := case when nullif(trim(coalesce(v_row->>'total_skid_capacity', '')), '') is null then null else (v_row->>'total_skid_capacity')::integer end;
    v_reserve := case when nullif(trim(coalesce(v_row->>'reserve_skids', '')), '') is null then null else (v_row->>'reserve_skids')::integer end;
    v_notes := nullif(trim(coalesce(v_row->>'notes', '')), '');
    if v_total is not null and v_total <= 0 then raise exception 'total_skid_capacity must be greater than zero.'; end if;
    if v_reserve is not null and v_reserve < 0 then raise exception 'reserve_skids cannot be negative.'; end if;

    insert into public.location_inventory_snapshots(
      location_id, snapshot_at, occupied_skids, total_skid_capacity, reserve_skids,
      source, source_file_name, notes, imported_by
    ) values (
      v_location.id, v_snapshot_at, v_occupied, v_total, v_reserve,
      'manual_csv', nullif(trim(coalesce(p_file_name, '')), ''), v_notes, auth.uid()
    )
    on conflict (location_id, snapshot_at, source) do update
    set occupied_skids = excluded.occupied_skids,
        total_skid_capacity = excluded.total_skid_capacity,
        reserve_skids = excluded.reserve_skids,
        source_file_name = excluded.source_file_name,
        notes = excluded.notes,
        imported_by = auth.uid(),
        created_at = now();

    update public.location_settings
    set current_occupied_skids = v_occupied,
        inventory_as_of = v_snapshot_at,
        skid_capacity = coalesce(v_total, skid_capacity),
        capacity_reserve_skids = coalesce(v_reserve, capacity_reserve_skids),
        capacity_last_source = 'mis_csv',
        updated_at = now()
    where location_id = v_location.id
      and (inventory_as_of is null or v_snapshot_at >= inventory_as_of);

    v_count := v_count + 1;
  end loop;

  insert into public.mis_import_runs(import_type, file_name, row_count, status, summary, imported_by)
  values (
    'inventory_snapshot', nullif(trim(coalesce(p_file_name, '')), ''), v_count,
    'completed', format('%s warehouse inventory snapshot row%s imported.', v_count, case when v_count = 1 then '' else 's' end), auth.uid()
  );

  update public.mis_integration_settings
  set last_success_at = now(), updated_by = auth.uid(), updated_at = now()
  where id = 1;

  return jsonb_build_object('imported_rows', v_count, 'file_name', p_file_name, 'status', 'completed');
end;
$$;

create or replace function public.admin_list_mis_import_runs()
returns table (
  id bigint,
  import_type text,
  file_name text,
  row_count integer,
  status text,
  summary text,
  imported_by_name text,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then raise exception 'You must be signed in to view MIS imports.'; end if;
  if not public.is_system_admin() then raise exception 'Only a MaxDock System Admin can view MIS imports.'; end if;

  return query
  select
    run.id,
    run.import_type,
    run.file_name,
    run.row_count,
    run.status,
    run.summary,
    coalesce(profile.full_name, profile.username, 'System Admin'),
    run.created_at
  from public.mis_import_runs run
  left join public.profiles profile on profile.id = run.imported_by
  order by run.created_at desc
  limit 20;
end;
$$;

revoke all on function public.admin_get_mis_integration_settings() from public, anon;
revoke all on function public.admin_save_mis_integration_settings(text, text, integer, text, text, text, time, boolean, text) from public, anon;
revoke all on function public.admin_import_inventory_snapshots(jsonb, text) from public, anon;
revoke all on function public.admin_list_mis_import_runs() from public, anon;
grant execute on function public.admin_get_mis_integration_settings() to authenticated;
grant execute on function public.admin_save_mis_integration_settings(text, text, integer, text, text, text, time, boolean, text) to authenticated;
grant execute on function public.admin_import_inventory_snapshots(jsonb, text) to authenticated;
grant execute on function public.admin_list_mis_import_runs() to authenticated;

insert into public.maxdock_schema_versions(version, description)
values ('DB-v14', 'Live appointment refresh, optional skid-capacity planning, and MIS inventory imports')
on conflict (version) do update
set description = excluded.description,
    applied_at = now();

commit;
