(function(){
"use strict";
const PAGE=document.body.dataset.page||"";
const $=id=>document.getElementById(id);
const imp=(el,p,v)=>el&&el.style.setProperty(p,v,"important");
function pair(id){const control=$(id);if(!control)return null;const host=control.closest(".filterField,.rangeMetric")||control.parentElement;if(!host)return null;host.classList.add("db66FieldPair");const label=host.querySelector(":scope > label,:scope > small");if(label&&label.tagName==="SMALL"){const next=document.createElement("label");next.htmlFor=id;next.textContent=label.textContent.trim();label.replaceWith(next)}return host}
function moveDashboardActions(){if(PAGE!=="dashboard")return;const filters=document.querySelector(".dashboardFilters");const primary=document.querySelector(".dashboardPrimaryActions");const utility=document.querySelector(".dashboardUtilityActions");const range=pair("dashboardRange");pair("adminDate");pair("adminStatus");if(filters&&primary&&range&&primary.parentElement!==filters)filters.insertBefore(primary,range);if(filters&&utility&&utility.parentElement!==filters)filters.appendChild(utility);const gear=document.querySelector("#dashboardCustomize,.dashboardCustomize");if(utility&&gear&&gear.parentElement!==utility){gear.classList.add("db66GearHost");utility.insertBefore(gear,utility.firstChild)}}
function harmonizeFields(){["adminDate","adminStatus","dashboardRange","queueDate","queueStatus","reportView","reportPreset","reportStart","reportEnd","myAppointmentFilter"].forEach(pair)}
function gridCount(container,varName){if(!container)return;const visible=[...container.children].filter(el=>!el.hidden&&getComputedStyle(el).display!=="none").length||1;container.style.setProperty(varName,String(visible))}
function harmonizeMetrics(){gridCount($("metrics"),"--db66-dashboard-columns");gridCount($("myAppointmentMetrics"),"--db66-appointment-columns");gridCount($("queueMetrics"),"--db66-queue-columns");gridCount($("reportMetrics"),"--db66-report-columns");const dashboard=$("metrics");if(dashboard)imp(dashboard,"grid-template-columns",`repeat(${Math.max(1,[...dashboard.children].filter(x=>!x.hidden).length)},minmax(0,1fr))`)}
function queueLayout(){if(PAGE!=="queue")return;pair("queueDate");pair("queueStatus");const actions=document.querySelector(".queueFilterActions");const utilities=document.querySelector(".pageUtilityActions");if(actions&&utilities){[...utilities.children].forEach(btn=>actions.appendChild(btn));utilities.remove()}}
function reportsLayout(){if(PAGE!=="reports")return;pair("reportView");pair("reportPreset");const filters=document.querySelector(".reportFilters");const gear=document.querySelector(".db64ReportCustomize");const pageUtilities=document.querySelector(".pageUtilityActions");if(filters&&pageUtilities){[...pageUtilities.children].forEach(btn=>filters.insertBefore(btn,gear||null));pageUtilities.remove()}}
function myAppointments(){if(PAGE==="myappointments")pair("myAppointmentFilter")}
function apply(){document.body.classList.add("db66Reference");harmonizeFields();moveDashboardActions();queueLayout();reportsLayout();myAppointments();harmonizeMetrics()}
function init(){apply();[80,220,500,1000,1800].forEach(t=>setTimeout(apply,t));["metrics","myAppointmentMetrics","queueMetrics","reportMetrics"].forEach(id=>{const el=$(id);if(el)new MutationObserver(()=>requestAnimationFrame(harmonizeMetrics)).observe(el,{childList:true,subtree:false,attributes:true,attributeFilter:["hidden","style"]})})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();